language: rust

rust:
  - stable
  - beta
  - nightly
  
env:
  - COLLECTD_VERSION=5.4
  - COLLECTD_VERSION=5.5
  - COLLECTD_VERSION=5.7

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true