[package]
name = "top-collectd-plugin"
version = "0.1.0"
authors = ["Jon Williams"]
edition = "2018"

[lib]
name = "top"
crate-type = ["cdylib"]

[dependencies]
collectd-plugin = "0.9.0"
glob = "0.2.11"
scan_fmt = "0.1.3"
shuteye = "^0"
sysconf = "0.3.4"

